In [1]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install pillow

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (2.4.6)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: matplotlib in ./.venv/lib/python3.14/site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.14/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pillow in ./.venv/lib/python3.14/site-packages (12.2.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [6]:
#Resize Dataset to 224×224
import os
from PIL import Image

dataset_path = "RP_lemonleaf"
output_path = "RP_lemonleaf_resized"

# create output folder
os.makedirs(output_path, exist_ok=True)

for folder in os.listdir(dataset_path):
    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):
        save_folder = os.path.join(output_path, folder)
        os.makedirs(save_folder, exist_ok=True)

        for file in os.listdir(folder_path):
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):

                img_path = os.path.join(folder_path, file)

                try:
                    img = Image.open(img_path)
                    img = img.convert("RGB")   # ensure 3 channels
                    img = img.resize((224, 224))  # resize here

                    img.save(os.path.join(save_folder, file))

                except:
                    pass

print("✅ All images resized to 224x224 successfully!")

✅ All images resized to 224x224 successfully!

In [7]:
import os
from PIL import Image

dataset_path = "IEEE_lemonleaf/Original_Dataset"
output_path = "IEEE_lemonleaf_resized"

# create output folder
os.makedirs(output_path, exist_ok=True)

for folder in os.listdir(dataset_path):
    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):
        save_folder = os.path.join(output_path, folder)
        os.makedirs(save_folder, exist_ok=True)

        for file in os.listdir(folder_path):
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):

                img_path = os.path.join(folder_path, file)

                try:
                    img = Image.open(img_path)
                    img = img.convert("RGB")   # ensure 3 channels
                    img = img.resize((224, 224))  # resize here

                    img.save(os.path.join(save_folder, file))

                except:
                    pass

print("✅ All images resized to 224x224 successfully!")

✅ All images resized to 224x224 successfully!

In [8]:
#Check pixel sizes
import os
import pandas as pd
from PIL import Image

dataset_path = "RP_lemonleaf_resized"

data = []

for folder in sorted(os.listdir(dataset_path)):
    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):
        image_count = 0
        sample_size = None

        for file in os.listdir(folder_path):
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                image_count += 1

                if sample_size is None:
                    img = Image.open(os.path.join(folder_path, file))
                    sample_size = img.size

        data.append([folder, image_count, sample_size])

df = pd.DataFrame(data, columns=["Class", "Number of Images", "Pixel Size"])
df

                                       Class  Number of Images  Pixel Size
0                                Anthracnose               609  (224, 224)
1                              Citrus_Canker               623  (224, 224)
2              Citrus_Greening_Huanglongbing               618  (224, 224)
3                           Citrus_Leaf_Curl               634  (224, 224)
4                           Citrus_Leafminer               650  (224, 224)
5                         Healthy Lemon Leaf               630  (224, 224)
6  Swallowtail Larval Herbivory (Deficiency)               630  (224, 224)

In [9]:
import os
import pandas as pd
from PIL import Image

dataset_path = "IEEE_lemonleaf_resized"

data = []

for folder in sorted(os.listdir(dataset_path)):
    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):
        image_count = 0
        sample_size = None

        for file in os.listdir(folder_path):
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                image_count += 1

                if sample_size is None:
                    img = Image.open(os.path.join(folder_path, file))
                    sample_size = img.size

        data.append([folder, image_count, sample_size])

df = pd.DataFrame(data, columns=["Class", "Number of Images", "Pixel Size"])
df

              Class  Number of Images  Pixel Size
0       Anthracnose               100  (224, 224)
1  Bacterial Blight               100  (224, 224)
2     Citrus Canker               100  (224, 224)
3        Curl Virus               100  (224, 224)
4   Deficiency Leaf               100  (224, 224)
5          Dry Leaf               100  (224, 224)
6      Healthy Leaf               100  (224, 224)
7       Sooty Mould               100  (224, 224)
8      Spider Mites               100  (224, 224)

In [10]:
#Merge two folder
import os
import shutil

dataset_paths = [
    "IEEE_lemonleaf_resized",
    "RP_lemonleaf_resized"
]

output_path = "lemonleaf"

os.makedirs(output_path, exist_ok=True)

for dataset in dataset_paths:
    for folder in os.listdir(dataset):
        src_folder = os.path.join(dataset, folder)

        if os.path.isdir(src_folder):
            dest_folder = os.path.join(output_path, folder)
            os.makedirs(dest_folder, exist_ok=True)

            for file in os.listdir(src_folder):
                if file.lower().endswith(('.jpg', '.jpeg', '.png')):

                    src_file = os.path.join(src_folder, file)

                    # avoid overwrite (important when merging datasets)
                    new_name = f"{dataset.split('/')[-1]}_{file}"
                    dest_file = os.path.join(dest_folder, new_name)

                    shutil.copy(src_file, dest_file)

print("✅ Both datasets merged into 'lemonleaf' successfully!")

✅ Both datasets merged into 'lemonleaf' successfully!

In [11]:
import os
import pandas as pd
from PIL import Image

dataset_path = "lemonleaf"

data = []

for folder in sorted(os.listdir(dataset_path)):
    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):
        image_count = 0
        sample_size = None

        for file in os.listdir(folder_path):
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                image_count += 1

                if sample_size is None:
                    img = Image.open(os.path.join(folder_path, file))
                    sample_size = img.size

        data.append([folder, image_count, sample_size])

df = pd.DataFrame(data, columns=["Class", "Number of Images", "Pixel Size"])
df

              Class  Number of Images  Pixel Size
0       Anthracnose               709  (224, 224)
1  Bacterial Blight               100  (224, 224)
2     Citrus Canker               723  (224, 224)
3        Curl Virus               734  (224, 224)
4   Deficiency Leaf               730  (224, 224)
5          Dry Leaf               100  (224, 224)
6      Healthy Leaf               730  (224, 224)
7       Sooty Mould               100  (224, 224)
8      Spider Mites               100  (224, 224)